name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
        
    - name: Run tests
      run: |
        pipenv run python test_gui.py
        
    - name: Build application
      run: |
        pipenv run pyinstaller video_organizer.spec
        
    - name: Create release package
      run: |
        mkdir -p release
        cd dist
        zip -r "../release/Skydiving_Video_Organizer_v${{ github.ref_name }}_macOS.zip" "Skydiving Video Organizer.app"
        cd ..
        
    - name: Create source package
      run: |
        zip -r "release/Skydiving_Video_Organizer_v${{ github.ref_name }}_source.zip" \
          video_organizer_gui.py \
          organize_videos.py \
          test_gui.py \
          build_app.sh \
          video_organizer.spec \
          Pipfile \
          Pipfile.lock \
          README.md \
          CHANGELOG.md \
          LICENSE
          
    - name: Generate checksums
      run: |
        cd release
        for file in *.zip; do
          shasum -a 256 "$file" > "${file}.sha256"
        done
        cd ..
        
    - name: Upload release assets
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/Skydiving_Video_Organizer_v${{ github.ref_name }}_macOS.zip
        asset_name: Skydiving_Video_Organizer_v${{ github.ref_name }}_macOS.zip
        asset_content_type: application/zip
        
    - name: Upload source package
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/Skydiving_Video_Organizer_v${{ github.ref_name }}_source.zip
        asset_name: Skydiving_Video_Organizer_v${{ github.ref_name }}_source.zip
        asset_content_type: application/zip
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Skydiving Video Organizer ${{ github.ref_name }}
        body: |
          ## What's New in ${{ github.ref_name }}
          
          This release includes:
          - Modern GUI application
          - Automatic video organization by date
          - Jump detection and grouping
          - Configurable settings
          - Name preservation option
          - Comprehensive logging
          
          ## Installation
          
          1. Download the ZIP file
          2. Extract and drag the app to your Applications folder
          3. Right-click and select "Open" (first time only)
          
          ## System Requirements
          
          - macOS 10.15 (Catalina) or later
          - 4GB RAM recommended
          - 1GB free disk space
          
          ## Support
          
          - Report issues: [GitHub Issues](https://github.com/${{ github.repository }}/issues)
          - Join discussions: [GitHub Discussions](https://github.com/${{ github.repository }}/discussions)
        draft: false
        prerelease: false 